# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:
{
   imports = [ ];

   boot.kernelModules                 = [ "kvm-amd" ];
   boot.extraModulePackages           = [];
   boot.initrd.kernelModules          = [];
   boot.initrd.availableKernelModules = [
      "ata_piix"
      "mptspi"
      "uhci_hcd"
      "ehci_pci"
      "ahci"
      "xhci_pci"
      "sd_mod"
      "sr_mod"
   ];

   fileSystems."/" = {
      device          = "/dev/disk/by-uuid/dde6bd93-93ed-44ff-b846-5bafa1fe8111";
      fsType          = "ext4";
   };

   swapDevices = [];

   networking.useDHCP                   = lib.mkDefault true;
   #networking.interfaces.ens33.useDHCP = lib.mkDefault true;
   nixpkgs.hostPlatform                 = lib.mkDefault "x86_64-linux";
}
